name: build
on:
  pull_request:
    paths:
      - 'data/**/*.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1'
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install 
        # if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: poetry run python makedb.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: success()
        with:
          commit_message: "build ctf.json"
