name: build
on:
  pull_request:
    paths:
      - 'data/**/*.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1'
      - run: poetry install && poetry run python makedb.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: success()
        with:
          commit_message: "build ctf.json"
