name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path
        working-directory: ./front
      - uses: actions/cache@v2
        id: cache-yarn
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
        working-directory: ./front
      - run: yarn build && yarn generate
        working-directory: ./front
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/dist



