name: deploy
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1'
      - run: poetry install && poetry run python makedb.py
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn && yarn build && yarn generate
        working-directory: ./front
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/dist



